server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: api-server
            uri: http://localhost:8081
            predicates:
              - Path=/api/**

  datasource:
    url: jdbc:mariadb://localhost:3307/user
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  threads:
    virtual:
      enabled: true

  jwt:
    secret: 8yuoweLFVFc1sBbByptPY4x1ooleo6Uk
    token:
      access_expiration: 7200000

logging:
  level:
    root: INFO
  file:
    name: ./logs/security-gateway-server.log